#!/bin/sh

set -e

case "$1" in
    purge)
        # Clean up script files on purge
        rm -f /usr/sbin/vcm.sh /usr/sbin/vcd.sh /usr/sbin/vcu.sh

        # Remove config database nodes
        if [ -x "/usr/sbin/omv-confdbadm" ]; then
            omv-confdbadm delete "conf.service.veracrypt" || :
        fi
        ;;
    remove)
        # Re-build workbench on package removal so menu disappears cleanly
        dpkg-trigger update-workbench
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
